//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 01:17:29 PM CEST 
//

package com.matt.artifact.packet;

import javax.activation.DataHandler;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlMimeType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data" type="{uri://matt.b/packet/}dataType" minOccurs="0"/>
 *         &lt;element name="images" type="{uri://matt.b/packet/}imagesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="arch" use="optional"/>
 *       &lt;attribute name="os" use="optional"/>
 *       &lt;attribute name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dateCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="dateModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
"data", "images"
})
@XmlRootElement(name = "packet")
public class Packet {

	@XmlMimeType("application/octet-stream")
	protected DataHandler data;
	protected ImagesType images;
	@XmlAttribute(name = "name", required = true)
	protected String name;
	@XmlAttribute(name = "description")
	protected String description;
	@XmlAttribute(name = "os")
	protected String os;
	@XmlAttribute(name = "arch")
	protected String arch;
	@XmlAttribute(name = "uri")
	@XmlSchemaType(name = "anyURI")
	protected String uri;
	@XmlAttribute(name = "version")
	protected String version;
	@XmlAttribute(name = "dateCreated")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar dateCreated;
	@XmlAttribute(name = "dateModified")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar dateModified;

	/**
	 * Gets the value of the data property.
	 * 
	 * @return possible object is {@link DataHandler }
	 * 
	 */
	public DataHandler getData() {
		return data;
	}

	/**
	 * Sets the value of the data property.
	 * 
	 * @param value
	 *            allowed object is {@link DataHandler }
	 * 
	 */
	public void setData(DataHandler value) {
		this.data = value;
	}

	/**
	 * Gets the value of the images property.
	 * 
	 * @return possible object is {@link ImagesType }
	 * 
	 */
	public ImagesType getImages() {
		return images;
	}

	/**
	 * Sets the value of the images property.
	 * 
	 * @param value
	 *            allowed object is {@link ImagesType }
	 * 
	 */
	public void setImages(ImagesType value) {
		this.images = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}
	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the os property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOs() {
		return os;
	}
	/**
	 * Sets the value of the os property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOs(String value) {
		this.os = value;
	}

	/**
	 * Gets the value of the arch property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArch() {
		return arch;
	}
	/**
	 * Sets the value of the arch property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArch(String value) {
		this.arch = value;
	}

	/**
	 * Gets the value of the uri property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUri() {
		return uri;
	}

	/**
	 * Sets the value of the uri property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUri(String value) {
		this.uri = value;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVersion(String value) {
		this.version = value;
	}

	/**
	 * Gets the value of the dateCreated property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDateCreated() {
		return dateCreated;
	}

	/**
	 * Sets the value of the dateCreated property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDateCreated(XMLGregorianCalendar value) {
		this.dateCreated = value;
	}

	/**
	 * Gets the value of the dateModified property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDateModified() {
		return dateModified;
	}

	/**
	 * Sets the value of the dateModified property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDateModified(XMLGregorianCalendar value) {
		this.dateModified = value;
	}

}
